### ISSUE TITLE
Does not pass batch_size, instead passes a boolean value (is_cuda)

### ISSUE THREAD

**Issue by shivashankarrs** [tongshuangwu/polyjuice#2]
https://github.com/tongshuangwu/polyjuice/blob/8328be98aa34f0ec3fa2aad62235bbcdccf06f3e/polyjuice/filters_and_selectors/perplex_filter.py#L99

**Comment by katiefraser** [comment]
Having the same issue.

**Comment by tongshuangwu** [comment]
Sorry, my bad. This should be fixed now in 2376e7b6a2d1fa18ec258c7ddd586628cfe550d1. Please let me know if you still run into problems!
