### ISSUE TITLE
Error while running demo notebook

### ISSUE THREAD

**Issue by esmab** [tongshuangwu/polyjuice#3]
Hi, I'm trying to run the "Polyjuice demo" notebook but getting an error about tensor sizes on the first call to pj.perturb(text). The only change I made to the code is to set is_cuda=False on both cell 1 and cell 2 since I am trying to run it on a CPU machine. Any help will be much appreciated! The full error message I'm getting is: 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/polyjuice/lib/python3.8/site-packages/transformers/tokenization_utils_base.py in convert_to_tensors(self, tensor_type, prepend_batch_axis)
    698                 if not is_tensor(value):
--> 699                     tensor = as_tensor(value)
    700 

ValueError: expected sequence of length 8 at dim 1 (got 9)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-3-a03991714638> in <module>
      5 # When running it for the first time, the wrapper will automatically
      6 # load related models, e.g. the generator and the perplexity filter.
----> 7 perturbations = pj.perturb(text)
      8 perturbations

~/repos/polyjuice/polyjuice/polyjuice_wrapper.py in perturb(self, orig_sent, blanked_sent, is_complete_blank, ctrl_code, perplex_thred, num_perturbations, verbose, **kwargs)
    258             eop = compute_edit_ops(orig_doc, generated_doc)
    259             if perplex_thred is not None:
--> 260                 pp = self._compute_delta_perplexity(eop)
    261                 is_vaild = pp.pr_sent < perplex_thred and pp.pr_phrase < perplex_thred
    262             if is_vaild and is_filter_code:

~/repos/polyjuice/polyjuice/polyjuice_wrapper.py in _compute_delta_perplexity(self, eops)
     94     def _compute_delta_perplexity(self, eops):
     95         if not self.validate_and_load_model("perplex_scorer"): return None
---> 96         return compute_delta_perplexity(eops, self.perplex_scorer, is_cuda=self.is_cuda)
     97 
     98     def _compute_sent_perplexity(self, sentence: str):

~/repos/polyjuice/polyjuice/filters_and_selectors/perplex_filter.py in compute_delta_perplexity(edit_ops, perplex_scorer, is_normalize, is_cuda)
    162         tuples += [(asent.text, aphrase.text), (bsent.text, bphrase.text)]
    163     #print(tuples)
--> 164     scores = compute_phrase_perplexity(tuples, perplex_scorer, 
    165         is_normalize=is_normalize, is_cuda=is_cuda)
    166     #print(scores)

~/repos/polyjuice/polyjuice/filters_and_selectors/perplex_filter.py in compute_phrase_perplexity(sentence_phrase_tuples, perplex_scorer, log, reduce, is_normalize, is_cuda)
    119         return scores
    120     model, tokenizer = perplex_scorer.model, perplex_scorer.tokenizer
--> 121     outputs = _tokens_log_prob([s[0] for s in sentence_phrase_tuples], model, tokenizer, is_cuda=is_cuda)
    122     for idx, (sentence, phrase) in enumerate(sentence_phrase_tuples):
    123         log_probs_all = outputs[idx][0]

~/repos/polyjuice/polyjuice/filters_and_selectors/perplex_filter.py in _tokens_log_prob(texts, model, tokenizer, batch_size, is_cuda)
     18         for i in range(0, len(texts), batch_size):
     19             batch = texts[i : i + batch_size]
---> 20             outputs.extend(_tokens_log_prob_for_batch(batch, model, tokenizer, is_cuda=is_cuda))
     21         return outputs
     22 

~/repos/polyjuice/polyjuice/filters_and_selectors/perplex_filter.py in _tokens_log_prob_for_batch(texts, model, tokenizer, is_cuda)
     25     outputs = []
     26     texts = [_add_special_tokens(text, tokenizer) for text in deepcopy(texts)]
---> 27     encoding = tokenizer.batch_encode_plus(texts, return_tensors='pt')
     28     with torch.no_grad():
     29         ids = encoding["input_ids"].to(device)

~/miniconda3/envs/polyjuice/lib/python3.8/site-packages/transformers/tokenization_utils_base.py in batch_encode_plus(self, batch_text_or_text_pairs, add_special_tokens, padding, truncation, max_length, stride, is_split_into_words, pad_to_multiple_of, return_tensors, return_token_type_ids, return_attention_mask, return_overflowing_tokens, return_special_tokens_mask, return_offsets_mapping, return_length, verbose, **kwargs)
   2493         )
   2494 
-> 2495         return self._batch_encode_plus(
   2496             batch_text_or_text_pairs=batch_text_or_text_pairs,
   2497             add_special_tokens=add_special_tokens,

~/miniconda3/envs/polyjuice/lib/python3.8/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py in _batch_encode_plus(self, *args, **kwargs)
    161         )
    162 
--> 163         return super()._batch_encode_plus(*args, **kwargs)
    164 
    165     def _encode_plus(self, *args, **kwargs) -> BatchEncoding:

~/miniconda3/envs/polyjuice/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py in _batch_encode_plus(self, batch_text_or_text_pairs, add_special_tokens, padding_strategy, truncation_strategy, max_length, stride, is_split_into_words, pad_to_multiple_of, return_tensors, return_token_type_ids, return_attention_mask, return_overflowing_tokens, return_special_tokens_mask, return_offsets_mapping, return_length, verbose)
    431         for input_ids in sanitized_tokens["input_ids"]:
    432             self._eventual_warn_about_too_long_sequence(input_ids, max_length, verbose)
--> 433         return BatchEncoding(sanitized_tokens, sanitized_encodings, tensor_type=return_tensors)
    434 
    435     def _encode_plus(

~/miniconda3/envs/polyjuice/lib/python3.8/site-packages/transformers/tokenization_utils_base.py in __init__(self, data, encoding, tensor_type, prepend_batch_axis, n_sequences)
    202         self._n_sequences = n_sequences
    203 
--> 204         self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
    205 
    206     @property

~/miniconda3/envs/polyjuice/lib/python3.8/site-packages/transformers/tokenization_utils_base.py in convert_to_tensors(self, tensor_type, prepend_batch_axis)
    713                         "Please see if a fast version of this tokenizer is available to have this feature available."
    714                     )
--> 715                 raise ValueError(
    716                     "Unable to create tensor, you should probably activate truncation and/or padding "
    717                     "with 'padding=True' 'truncation=True' to have batched tensors with the same length."

ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.

**Comment by esmab** [comment]
I resolved the issue by changing line 27 in perplex_filter to: encoding = tokenizer.batch_encode_plus(texts, return_tensors='pt', truncation=True, padding=True)

**Comment by tongshuangwu** [comment]
thanks for spotting this! I've fixed it in https://github.com/tongshuangwu/polyjuice/commit/b9f544d02c4330f1b10bacaa5c0e5bb8a7811eb2.
