### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Dennis1989** [tongshuangwu/polyjuice#6]
I get the mentioned error when trying to execute your notebook examples:

```
perturbations = pj.perturb(text)
perturbations
```

**Comment by tongshuangwu** [comment]
Hi there! Sorry for my late response, but if you pull from main, this should be fixed. Looks like the latest transformer version made the API not compatible anymore. For more discussions, please see: https://github.com/tongshuangwu/polyjuice/issues/7
